[build]
  publish = "docs"
  command = "echo 'No build needed'"

[functions]
  directory = "docs/netlify/functions"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
