[build]
  publish = "docs"
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/webhook.html"
  to = "/.netlify/functions/webhook"
  status = 200
